CATEGORIES = [
    ("Accommodation_Space", "Accommodation and Space"),
    ("Advice_Tuition", "Advice and Tuition"),
    ("Animals_Pets", "Animals and Pets"),
    ("Appliances_Furniture", "Appliances and Furniture"),
    ("Artisans_Specialists", "Artisans and Specialists"),
    ("Arts_Crafts", "Arts and Crafts"),
    ("Body_Mind", "Body and Mind"),
    ("Books_Publications", "Books and Publications"),
    ("BusinessServices", "BusinessServices"),
    ("Care_Assistance", "Care and Assistance"),
    ("CESServices", "CESServices"),
    ("Clothing_Apparel", "Clothing and Apparel"),
    ("Community", "Community"),
    ("Companionship", "Companionship"),
    ("Computer_IT", "Computer and IT"),
    ("Electronics", "Electronics"),
    ("Entertainment_Recreation", "Entertainment and Recreation"),
    ("Food_Drink", "Food and Drink"),
    ("Gardening_Agriculture", "Gardening and Agriculture"),
    ("Goods", "Goods"),
    ("Hiring_Borrowing", "Hiring and Borrowing"),
    ("HomeServices", "HomeServices"),
    ("Labour_Assistance", "Labour and Assistance"),
    ("Media_Advertising", "Media and Advertising"),
    ("Miscellaneous", "Miscellaneous"),
    ("MotorVehicle", "Motor Vehicle"),
    ("OfficeEquipment", "Office Equipment"),
    ("PersonalServices", "Personal Services"),
    ("Toys", "Toys"),
    ("Transport", "Transport"),
]

SAMPLE_OFFERINGS = [
    ["Food_Drink", "rice", "Matta rice", "50$ per kg"],
    ["Food_Drink","coconut","Thenga. Coconut for chutney and curry.","20$ per piece"],
    ["Food_Drink", "egg", "Egg recipies per piece", "8$ per piece"],
    ["Food_Drink", "brinjal", "Vazhuthanangal, per kg", "20$ per kg"],
    ["Food_Drink", "mulak_podi", "Mulaku podi per 100gram", "40$ per 100grams"],
    ["Food_Drink", "salt", "uppu per kg", "20$ per kg"],
    ["Electronics", "earphone", "Earphone", "800$ per piece"],
    ["Electronics", "mp3_player", "MP3 Player for listening songs", "5000$ per piece"],
    ["Electronics", "solarpanel", "Solar panel", "2000$ per piece"],
    ["Clothing_Apparel", "underwear", "UnderWear", "200$ per piece"],
    ["Clothing_Apparel", "tracksuit", "Track suit pants", "600$ per piece"],
    ["Clothing_Apparel", "tshirt", "Tshirt", "300$ per piece"],
    ["Accommodation_Space", "land", "25 meter/sq land", "50000$ per cent"],
    ["Accommodation_Space", "room_rent", "Room rent/month", "5000$ per month"],
]

SAMPLE_USERS = [
    'afsal', 'ajmal', 'ameen', 'ansaf', 'ansar', 'ansif', 'ansil','ansiya','ayaan', 'basith', 'diya',
    'doulath','faseela', 'fazal', 'fouziya','hair', 'hamza','hiba','hisana','ishanu','jasmin','jina',
    'kadeeja','kunjumuthu','lulu','meerankutty','moosa','mufeed','mumthaj','najath','najma','nasar',
    'naseema','naseer', 'nazal','neema','nihal','nishad', 'nusra', 'rafeena','rasiya','resi','rubeena',
    'sabeela','sabeena','saji','saleem','samrin','shahana','shaira','shakeer','shami','shamsu','shihas',
    'sofi', 'sumayya','shakeer','sufail','suhail','sulaiman','vaheedha'
]