# Generated by Django 5.1.1 on 2025-12-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stellar_secret',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
