# Generated by Django 5.1.1 on 2025-05-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0002_remove_userverification_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='', upload_to='users/'),
            preserve_default=False,
        ),
    ]
