# Generated by Django 5.1.1 on 2025-02-28 11:01

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0002_listing_img_transaction_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=25, scale=None, size=[500, 300], upload_to='offering/%Y/%m/%d/'),
        ),
    ]
