# Generated by Django 5.1.1 on 2025-12-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0002_user_stellar_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stellar_secret',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
