# Generated by Django 5.1.1 on 2025-04-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0002_remove_exchange_created_by_userverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offering/%Y/%m/%d/'),
        ),
    ]
